# Steps
* 1 make a mini program without RE expressions
* 2 use regualr expression to make the aboe mini program less bloated. 
* 3 end of chapter program with have us extract phone numbers and emails from ablock of text.

# Finding patters of text withhout expressions
find an american phone number in a string:
* three numbers
* a hyphen
* three numbers
* a hyphen
* four numbers
* example: 123-123-1234

In [1]:
def isPhoneNumber(text):
    if len(text) != 12:
        return False
    for i in range(0,3):
        if not text[i].isdecimal():
            return False
    if text[3] != '-':
        return False
    for i in range(4,7):
        if not text[i].isdecimal():
            return False
        if text[7] != '-':
            return False
    for i in range(8, 12):
        if not text[i].isdecimal():
            return False
    return True

print("Is 415-555-4242 a phone number?")
print(isPhoneNumber('415-555-4242'))
print("Is Mishi mishi a phone number?")
print(isPhoneNumber('Mishi mishi'))

Is 415-555-4242 a phone number?
True
Is Mishi mishi a phone number?
False


replaced the last four line of code with a string message to pull a number from that string

In [2]:
def isPhoneNumber(text):
    if len(text) != 12:
        return False
    for i in range(0,3):
        if not text[i].isdecimal():
            return False
    if text[3] != '-':
        return False
    for i in range(4,7):
        if not text[i].isdecimal():
            return False
        if text[7] != '-':
            return False
    for i in range(8, 12):
        if not text[i].isdecimal():
            return False
    return True

message = 'Call me at 415-555-1011 tomorrow, 415-555-9999 is my office.'
for i in range(len(message)):
    chunk = message[i:i+12]
    if isPhoneNumber(chunk):
        print('Phnone number found: ' + chunk)
print('Done')

Phnone number found: 415-555-1011
Phnone number found: 415-555-9999
Done


# Import the RE module and Creat REGEX Objects

In [3]:
import re

passing a string value representing your regular expression to re.compile() returns a Regex pattern object(or simply a Regex object.)
Rember that \d means 'A digital character' and \d\d\d-\d\d\d-\d\d\d\d is the regualr expression for a phone number pattern.

In [4]:
phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')

The below code does the same thing as our above isPhoneNumber function above

In [5]:
mo = phoneNumRegex.search('My number is 415-555-4242.')
print("Phone number found: " + mo.group())

Phone number found: 415-555-4242


.search() method is tell our REGEX object to seach a particular string

.group() method will display the wole match.

# Review of Regualr exprresion Match:
1) Import the regex module with import re

2) Create a Regex object with the re.compile() function. (Remember to use a raw string)

3) Pass the string you want to search intp the Regex onject's search() method. This returns a m Match object.

4) Call the Match object's group() method to return a string of the actual matched text.

REGEX tester can be found at:

https://pythex.org/

# More Patter Matching with Regualr Expressions

Group with parentheses
* more .group() method examples

In [6]:
textString = 'My number is 415-555-4242.'

phoneNumRegex2 = re.compile(r'(\d\d\d)-(\d\d\d)-(\d\d\d\d)')
mo2 = phoneNumRegex2.search(textString)
mo2.group(1)

'415'

In [7]:
mo2.group(2)

'555'

In [8]:
mo2.group(3)

'4242'

In [9]:
mo2.group()

'415-555-4242'

In [10]:
mo2.groups()

('415', '555', '4242')

In [11]:
phoneNumRegex3 = re.compile(r'(\d\d\d)-(\d\d\d-\d\d\d\d)')
mo3 = phoneNumRegex3.search('My number is 415-555-4242.')

In [12]:
mo3.groups()

('415', '555-4242')

Above code makes a tuple of multiple values so we can assign each value like so:

In [13]:
areaCode, mainNumber = mo3.groups()
print(areaCode)
print(mainNumber)

415
555-4242


We may need to have chars that python usually ignore like the "\". Here is how we can do this:

In [14]:
phoneNumRegex4 = re.compile(r'(\(\d\d\d\)) (\d\d\d-\d\d\d\d)')
mo4 = phoneNumRegex4.search('My phone number is (415) 555-4242.')
mo4.group(1)

'(415)'

In [15]:
mo4.group(2)

'555-4242'

# The following Chars in REGEX expression have special meanings:
* .
* ^
* *
* +
* ?
* }
* {
* [
* ]
* \
* |
* (
* )
To detect the above special charecters in a RE expression we will have to use the balvkslah char "\\" to escape them

Common mistake is to forget to cloth a REGEX by accidently puting or not putting the correct number of backslashes.
Below is an example:

In [16]:
re.compile(r'(\(Parentheses\)')

error: missing ), unterminated subpattern at position 0

***error: missing ), unterminated subpattern at position 0***

The above erros tells us tha there is an openinf parenthesis at the index 0 of the r'(\(Parentheses\)' string that is missing its correspning closing parenthesis.

# Mathing Multiple Groups with the pipe
the " | " character is called a ***pipe***
* the pipe "|" can be used anywhere you want to match one of many expressions
***example:***
r'Batman|Tina Fey' will match either 'Batman' or 'Tina Fey'

When both Batman and Tina Fey are in the same string only teh first occurance of matching text will be returned as the matching object.

In [17]:
heroRegex = re.compile(r'Batman|Tina Fey')
mo5 = heroRegex.search('Batman and Tina Fey')
mo5.group()

'Batman'

In [18]:
mo6 = heroRegex.search('Tina Fey and Batman')
mo6.group()

'Tina Fey'

We can finall all mataching occurances by useing .findall() method

In [19]:
mo7 = heroRegex.findall("Batman and Tina Fey")
mo7

['Batman', 'Tina Fey']

There is a way to find matchs using part of word for everything that goes with it.

for example batman, batmobile, batcoper, batbat

In [20]:
batRegex = re.compile(r'bat(man|mobile|coper|bat)')
mo8 = batRegex.search('batmobile lost a whell')
mo8.group()

'batmobile'

In [21]:
mo8.group(1)

'mobile'

# Optional MAtching with the Question Mark
The "?" character flags the group the ***precedes*** the question mark as an optional part of the pattern.
* We can think of the ? as saying: Match zero or one of the group preceding this question mark.

In [22]:
batRegex2 = re.compile(r'bat(wo)?man')
mo9 = batRegex2.search('The adventures of batman')
mo9.group()

'batman'

In [23]:
mo10 = batRegex2.search('The adventures of batwoman')
mo10.group()

'batwoman'

Marke the area code of a number optional from our previous exampeles:

In [24]:
phoneRegexArea = re.compile(r'(\d\d\d-)?\d\d\d-\d\d\d\d')
mo11 = phoneRegexArea.search('My number is 123-555-1234')
mo11.group()

'123-555-1234'

In [25]:
mo12 = phoneRegexArea.search('My number is 555-1234')
mo12.group()

'555-1234'

# Matching zero or more with a star '*'
The '*' (called the star or asterisk) means: match zero or more--The group that ***precedes*** the star can occure any number of times in the text.

In [26]:
batRegexStar = re.compile(r'Bat(wo)*man')
mo13 = batRegexStar.search('The Adventures of Batman')
mo13.group()

'Batman'

In [27]:
mo14 = batRegexStar.search('The Adventures of Batwoman')
mo14.group()

'Batwoman'

In [28]:
mo15 = batRegexStar.search('The adventures of Batwowowowowowoman')
mo15.group()

'Batwowowowowowoman'

# Matching One or more with the plus
The '+' means to match one or more
unlike the start which does not require its group to appear in the matched string, the group preceding a plus '+' sign ***must appear at least once. Not optional***

In [29]:
batRegexPlus = re.compile(r'Bat(wo)+man')
mo16 = batRegexPlus.search('The Adventure os Batwoman')
mo16.group()

'Batwoman'

In [30]:
mo17 = batRegexPlus.search('The Adventures of Batwowowowowoman')
mo17.group()

'Batwowowowowoman'

In [31]:
mo18 = batRegexPlus.search('The Adventues of Batman')
mo18 == None

True

# Matching Specific Repetitions with Brace
{} will match a spefic number of times for the value before it. Example:
(ha){3} eould match hahaha but not haha because ha did not have 3 toegeher ad haha only has two.

If we need a range we can do so by adding a comma. and the the max number needed. Example:
(ha){3,5} will match a mine of three hahaha but will also match hahahaha or hahahahaha 

or
we could do {3, } and this woul match a min of 3 and up

vs
{ , 5} would match a min of one but no more than 5

In [32]:
haRegex = re.compile(r'(Ha){3}')
mo19 = haRegex.search('HaHaHa')
mo19.group()

'HaHaHa'

In [33]:
mo20 = haRegex.search('Ha')
mo20 == None

True

# Greedy and non-Greedy Matching
Pythons RE are greedy by default meaning that in ambiguous situatuons they will match the longest string possiable.

The ***non-Greedy*** (also called lazy) version of the braces, which matches the shortest string possible, has a closing brace followed by a question mark.

In [34]:
greedyRegex = re.compile(r'(Ha){3,5}')
mo21 = greedyRegex.search("HaHaHaHaHa")
mo21.group()

'HaHaHaHaHa'

In [35]:
nongreedyRegex = re.compile(r'(Ha){3,5}?')
mo22 = nongreedyRegex.search("HaHaHaHaHa")
mo22.group()

'HaHaHa'

# Note
The a question mark can have two meaning in regular expressions: ***declaring non-greedy match*** or ***flagging an optional group. (zero or 1)***

# The findall() Method
method will return the strings of every match in the searched string

In [40]:
# using .search()
# returns a Match object only on the first instance of matching text
phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
mo23 = phoneNumRegex.search('Cell: 415-555-9999 Work: 212-555-0000')
mo23.group()

'415-555-9999'

In [42]:
# using findall()
# will not return a Match object but a list of strings—as long as there are no groups in the regular expression.
phoneFNumRegex = re.compile(r'(\d\d\d)-(\d\d\d)-(\d\d\d\d)') # has groups
phoneFNumRegex.findall('Cell: 415-555-9999 Work: 212-555-9990')

[('415', '555', '9999'), ('212', '555', '9990')]

In [43]:
phoneFNumRegex2 = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d') # has no groups
phoneFNumRegex2.findall('Cell: 415-555-9999 Work: 212-555-9990')

['415-555-9999', '212-555-9990']

### To summarize what the findall() method returns, remember the following:

* When called on a regex with no groups, such as \d\d\d-\d\d\d-\d\d\d\d, the method findall() returns a ***list of string matches***, such as ['415-555-9999', '212-555-0000'].
* When called on a regex that has groups, such as (\d\d\d)-(\d\d\d)-(\d\d\d\d), the method findall() returns a ***list of tuples of strings*** (one string for each group), such as [('415', '555', '9999'), ('212', '555', '0000')].

# Character Classes
In the earlier phone number regex example, you learned that \d could stand for any numeric digit. That is, \d is shorthand for the regular expression (0|1|2|3|4|5|6|7|8|9). There are many such shorthand character classes, as shown in Table 7-1.

Table 7-1: Shorthand Codes for Common Character Classes

Shorthand character class

Represents

***\d*** -------> Any numeric digit from 0 to 9.

***\D*** -------> Any character that is ***NOT*** a numeric digit from 0 to 9.

***\w*** -------> Any letter, numeric digit, or the underscore character. (Think of this as matching “word” characters.)

***\W*** -------> Any character that is ***NOT*** a letter, numeric digit, or the underscore character.

***\s*** -------> Any space, tab, or newline character. (Think of this as matching “space” characters.)

***\S*** -------> Any character that is ***NOT*** a space, tab, or newline.


Character classes are nice for shortening regular expressions. The character class [0-5] will match only the numbers 0 to 5; this is much shorter than typing (0|1|2|3|4|5). Note that while \d matches digits and \w matches digits, letters, and the underscore, there is no shorthand character class that matches only letters. (Though you can use the [a-zA-Z] character class, as explained next.)


In [46]:
xmasRegex = re.compile(r'\d\s\w+')
xmasRegex.findall("12 drummers, 11 pipers, 10 lords, 9 ladies, 8 maids, 7 swans, 6 geese, 5 rings, 4 bird, 3 hens, 2 doves, 1 partridge")

['2 drummers',
 '1 pipers',
 '0 lords',
 '9 ladies',
 '8 maids',
 '7 swans',
 '6 geese',
 '5 rings',
 '4 bird',
 '3 hens',
 '2 doves',
 '1 partridge']

#### What above is doing:
* The regular expression \d+\s\w+ will match text that has one or more numeric digits (\d+), 
* followed by a whitespace character (\s), 
* followed by one or more letter/digit/underscore characters (\w+). 
* The findall() method returns all matching strings of the regex pattern in a list.

# Making Your Own Character Classes
There are times when you want to match a set of characters but the shorthand character classes (\d, \w, \s, and so on) are too broad. 

You can define your own character class using square brackets. For example, the character ***class [aeiouAEIOU]*** will match any vowel, both lowercase and uppercase

In [47]:
vowelRegex = re.compile(r'[aeiouAEIOU]')
vowelRegex.findall("RoboCop easts baby food. BABYFOOD")

['o', 'o', 'o', 'e', 'a', 'a', 'o', 'o', 'A', 'O', 'O']

You can also include ranges of letters or numbers by using a hyphen. 

For example, the character ***class [a-zA-Z0-9]*** will match all lowercase letters, uppercase letters, and numbers.

Note that inside the square brackets, the normal regular expression symbols are not interpreted as such. This means you do not need to escape the ., *, ?, or () characters with a preceding backslash. For example, ***the character class [0-5.] will match digits 0 to 5 and a period. You do not need to write it as [0-5\.].***

By placing a caret character (^) just after the character class’s opening bracket, you can make a negative character class. 
***A negative character class will match all the characters that are not in the character class.***

By placing a ***caret character*** (^) just after the character class’s opening bracket, you can make a ***negative character*** class.

* A negative character class will match all the characters that are not in the character class

In [49]:
consonsantRegex = re.compile(r'[^aeiouAEIOU]')
consonsantRegex.findall('RoboCop eats babyfood. BABYFOOD')
# Now, instead of matching every vowel, we’re matching every character that isn’t a vowel.

['R',
 'b',
 'C',
 'p',
 ' ',
 't',
 's',
 ' ',
 'b',
 'b',
 'y',
 'f',
 'd',
 '.',
 ' ',
 'B',
 'B',
 'Y',
 'F',
 'D']

# The Caret and Dollar Sign Characters
You can also use the caret symbol (^) at the start of a regex to indicate that a match ***must occur at the beginning of the searched text***. 

Likewise, you can put a dollar sign ($) at the end of the regex to indicate the ***string must end with this regex pattern.*** 

And

You can use the ^ and $ together to indicate that the ***entire string must match the regex—that is, it’s not enough for a match to be made on some subset of the string.***

* For example, the r'^Hello' regular expression string matches strings that begin with 'Hello'.

In [60]:
beginsWithHello = re.compile(r'^Hello')
begin = beginsWithHello.search('Hello, world!')
begin.group()

'Hello'

The ***r'\d$'*** regular expression string matches strings that end with a numeric character from 0 to 9

In [61]:
endsWithNum = re.compile(r'\d$')
ends = endsWithNum.search('Your number is 42')
ends.group()

'2'

In [62]:
endsWithNum = re.compile(r'\d$')
ends = endsWithNum.search('Your number is forty two')
ends == None

True

The ***r'^\d+$'*** regular expression string matches strings that both begin and end with one or more numeric characters

In [65]:
wholeNumString = re.compile(r'\d+$')
wholeNum = wholeNumString.search('1234567890')
wholeNum.group()

'1234567890'

In [66]:
wholeNumString2 = re.compile(r'\d+$')
wholeNum2 = wholeNumString2.search('12 3456 789 0')
wholeNum2.group()

'0'

In [67]:
wholeNumString3 = re.compile(r'\d+$')
wholeNum3 = wholeNumString3.search('123456xyz7890')
wholeNum3.group()

'7890'

The last two search() calls in the previous interactive shell example demonstrate how the entire string must match the regex if ^ and $ are used.

I always confuse the meanings of these two symbols, so I use the mnemonic ***“Carrots cost dollars”*** to remind myself that the ***caret comes first and the dollar sign comes last***

# The Wildcard Character
The ***. (or dot)*** character in a regular expression is called a wildcard and will match any character except for a newline

In [69]:
dotRegex = re.compile(r'.at')
dotIt = dotRegex.search('The cat in the hat sat on a flat mat')
dotIt.group()

'cat'

In [70]:
dotRegex = re.compile(r'.at')
dotRegex.findall('The cat in the hat sat on a flat mat')


['cat', 'hat', 'sat', 'lat', 'mat']

Remember that the dot character will match just one character, which is why the match for the text flat in the previous example matched only lat. To match an actual dot, escape the dot with a backslash: \..

* Also seems like if we do it by group we only get the first match

# Matching Everything with Dot-Star
dot-star (.*) to stand in for that “anything.” Remember that the 
* dot character means “any single character except the newline,” 

and the 
* star character means “zero or more of the preceding character.”

In [71]:
nameRegex = re.compile(r'First Name:(.*) Last Name:(.*)')
name = nameRegex.search('First Name: JQT Last Name: S')
name.group()

'First Name: JQT Last Name: S'

In [75]:
nameRegex2 = re.compile(r'First Name:?(.*) Last Name:?(.*)')
name2 = nameRegex2.search('First Name: JQT Last Name S')
name2.group()

'First Name: JQT Last Name S'

The dot-star uses greedy mode: It will always try to match as much text as possible. To match any and all text in a non-greedy fashion, use the dot, star, and question mark (.*?). 

Like with braces, the question mark tells Python to match in a non-greedy way

In [76]:
notGreedyRegex = re.compile(r'<.*?>')
notGreed = notGreedyRegex.search('<To serve man> for dinner.>')
notGreed.group()

'<To serve man>'

In [78]:
GreedyRegex2 = re.compile(r'<.*>')
Greed2 = GreedyRegex2.search('<To serve man> for dinner.>')
Greed2.group()

'<To serve man> for dinner.>'

Both regexes roughly translate to “Match an opening angle bracket, followed by anything, followed by a closing angle bracket.” But the string '<To serve man> for dinner.>' has two possible matches for the closing angle bracket. 
    
* In the non-greedy version of the regex, Python matches the shortest possible string: '<To serve man>'.
    
* In the greedy version, Python matches the longest possible string: '<To serve man> for dinner.>'.

# Matching Newlines with the Dot Character
The dot-star will match everything except a newline. By passing re.DOTALL as the second argument to re.compile(), you can make the dot character match all characters, including the newline character.

In [79]:
noNewLineRegex = re.compile('.*')
NoNewLines = noNewLineRegex.search('Serve the public Trust. \n Protect the innocent. \n Uphold the law.')
NoNewLines.group()

'Serve the public Trust. '

In [81]:
NewLineRegex = re.compile('.*', re.DOTALL)
NewLines = NewLineRegex.search('Serve the public Trust. \n Protect the innocent. \n Uphold the law.')
NewLines.group()

'Serve the public Trust. \n Protect the innocent. \n Uphold the law.'

* The regex noNewlineRegex, which did not have re.DOTALL passed to the re.compile() call that created it, will match everything only up to the first newline character, 

whereas 

* newlineRegex, which did have re.DOTALL passed to re.compile(), matches everything. This is why the newlineRegex.search() call matches the full string, including its newline characters

# Review of Regex Symbols

* The ? matches zero or one of the preceding group.
* The * matches zero or more of the preceding group.
* The + matches one or more of the preceding group.
* The {n} matches exactly n of the preceding group.
* The {n,} matches n or more of the preceding group.
* The {,m} matches 0 to m of the preceding group.
* The {n,m} matches at least n and at most m of the preceding group.
* {n,m}? or *? or +? performs a non-greedy match of the preceding group.
* ^spam means the string must begin with spam.
* spam$ means the string must end with spam.
* The . matches any character, except newline characters.
* \d, \w, and \s match a digit, word, or space character, respectively.
* \D, \W, and \S match anything except a digit, word, or space character, respectively.
* [abc] matches any character between the brackets (such as a, b, or c).
* [^abc] matches any character that isn’t between the brackets.

# Case-Insensitive Matching
Normally, regular expressions match text with the exact casing you specify. For example, the following regexes match completely different strings

But sometimes you care only about matching the letters without worrying whether they’re uppercase or lowercase. To make your regex case-insensitive, you can pass re.IGNORECASE or re.I as a second argument to re.compile()

In [82]:
robocop = re.compile(r'robocop', re.I)
robocop.search('Robocop is part man, part machine, all cop').group()

'Robocop'

In [83]:
robocop2 = re.compile(r'robocop', re.I)
robocop2.search('ROBOCOP is part man, part machine, all cop').group()

'ROBOCOP'

In [85]:
robocop3 = re.compile(r'robocop', re.I)
robocop3.search('Al, why does your programing talk about robocop so much?').group()

'robocop'

# Substituting Strings with the sub() Method
Regular expressions can not only find text patterns but can also substitute new text in place of those patterns. 

* The sub() method for Regex objects is passed two arguments. 

The first argument is a string to replace any matches. The second is the string for the regular expression. The sub() method returns a string with the substitutions applied.

In [88]:
subRegex = re.compile(r'Agent \w+')
subRegex.sub('CENSORED', 'Agent Alice gave the secret documents to Agent Bob')

'CENSORED gave the secret documents to CENSORED'

Sometimes you may need to use the matched text itself as part of the substitution. In the first argument to sub(), you can type \1, \2, \3, and so on, to mean “Enter the text of group 1, 2, 3, and so on, in the substitution.”

For example, say you want to censor the names of the secret agents by showing just the first letters of their names. To do this, you could use the regex Agent (\w)\w* and pass r'\1****' as the first argument to sub(). The \1 in that string will be replaced by whatever text was matched by group 1—that is, the (\w) group of the regular expression.

In [95]:
sub1Regex = re.compile(r'Agent (\w)\w*')
sub1Regex.sub(r'\1****', 'Agent Alice told Agent Carol that Agent Eve knew Agent Bob was a double agent')

'A**** told C**** that E**** knew B**** was a double agent'